Iiscrum 89 zabbix
digiaiiris/zabbix pull request #3
Opened 2019-10-18 10:35 UTC by PeterJokinen

Zabbix changes for testing tool, to easily recreate it's patch file. See PR [here ](https://github.com/digiaiiris/iiris/pull/1018)for more.

2019-10-21 08:51 UTC, sapajune approved these changes

2019-10-21 08:51 UTC, sapajune commented on frontends/php/items.php
> +					' VALUES ('.implode(',', array_values($item)).')';
Does this work for text values? I would assume text values should be in single quotes.

Also, this should probably include some SQL injection prevention.

2019-10-21 08:51 UTC, sapajune commented on frontends/php/items.php
> +			$sql_select = 'SELECT * FROM item_testing WHERE itemid='.$itemid;
Should have SQL injection prevention.

2019-10-21 08:51 UTC, sapajune commented on frontends/php/include/schema.inc.php
> +	],
Creation statement for required additional table should be implemented somehow.

2019-10-21 08:52 UTC, sapajune requested changes
See comments.

2019-10-31 08:27 UTC, PeterJokinen commented on frontends/php/items.php
> +					' VALUES ('.implode(',', array_values($item)).')';
This does indeed work for text values. Results in strings encased with single quotes.

Didi some digging in Zabbix, I figured zabbix must have some sql injection prevention methods, and turns out it does. Found a function in zabbix([zbx_dbstr](https://github.com/zabbix/zabbix/blob/783cc48bba613df229b45fab9e6e486717d7e892/frontends/php/include/db.inc.php#L986)), that escapes strings for safe sql use. So I added checks for all string values for this sql.

2019-10-31 08:33 UTC, sapajune commented on frontends/php/items.php
> +					' VALUES ('.implode(',', array_values($item)).')';
Good to know. That method handles escapes needed for different database drivers nicely.

2019-10-31 10:44 UTC, PeterJokinen commented on frontends/php/items.php
> +			$sql_select = 'SELECT * FROM item_testing WHERE itemid='.$itemid;
Handled by zabbix data type checks, as 'group_itemid' is an integer and cannot be changed to string

2019-11-19 10:43 UTC, PeterJokinen commented on frontends/php/include/schema.inc.php
> +	],
Added table creation sql to the other [PR](https://github.com/digiaiiris/iiris/pull/1018), have a look there.

2019-11-19 11:21 UTC, sapajune commented on frontends/php/include/schema.inc.php
> +	],
Works nicely for our Ansible setup. I suggest also including the table create script in this project (without USE row) with some comments/documentation.

2019-11-25 10:39 UTC, PeterJokinen commented on frontends/php/include/schema.inc.php
> +	],
added table creation script to this PR also

2019-12-02 10:58 UTC, PeterJokinen commented
Ping @bulkware @sapajune 
Changes has been made, ready for re-review

2019-12-02 11:02 UTC, sapajune approved these changes

2019-12-02 11:04 UTC, bulkware approved these changes

2019-12-02 11:09 UTC, merged